### PR TITLE
Allow ignoring specified @Beta interfaces

### LINKED ISSUE #1: Add configuration to ignore specific @Beta interfaces
Apache jclouds uses Guava `TypeToken` and `Futures.immediateFuture` extensively which crowds out other output from library-detectors.  Providing configuration to ignore user-specified interfaces would allow us to see the other uses of @Beta interfaces.

### PR DESCRIPTION
**Pull request by andrewgaul**
FindBugs does not provide a plugin configuration mechanism so we use
the system properties instead.  Note that this functionality requires
setting jvmArgs in the findbug-maven-plugin configuration stanza.
Fixes #1.

### CODE REVIEW

**Comment by milleruntime** [comment]
Any hope of merging this pull request? The Accumulo project has interest in using the plugin but ran into this same problem. See reference above.

**Comment by andrewgaul** [comment]
@baens @brocarlson @majgis Does Overstock have a maintainer who can merge this and push a release?

**Comment by majgis** [comment]
@andrewgaul I will ask around...

**Comment by baens** [comment]
Looks good to me, I'll get this published here as soon as I can.

**Comment by milleruntime** [comment]
Thank you, we are excited to use this plugin.

**Comment by baens** [comment]
Bear with me a little bit, this has been a little bit trickier to deploy then I thought. But I am working on it!

**Comment by irobertson** [comment]
Erik, let me know if I can offer any assistance. Deploying to sonatype's
oss server can be a bit daunting the first time :).

**Comment by milleruntime** [comment]
@baens Did a new release of this plugin get published?

**Comment by baens** [comment]
@milleruntime thank you thank you for your patients. I have still failed to published and have spent an embarrsing amount of time trying.

@irobertson can you take a try please? The instructions have seem to have changed from the last time (...years ago...) I've tried this and I seem to be playing error wack-a-mole...

**Comment by irobertson** [comment]
I'd be happy to take a stab at this; can you add me as a collaborator to repository so that I can run the maven release plugin? I can also update the changes.xml file, and the https://overstock.github.io/library-detectors/ page.

**Comment by milleruntime** [comment]
@irobertson thanks for stepping up.  Any progress on a release?

**Comment by irobertson** [comment]
Thanks for the prod. I finally figured it out; they've changed a fair
amount since the last time I did this. In any case, version 1.2.0 has been
released, and the project site (FWIW) is updated at
http://overstock.github.io/library-detectors/index.html.
<http://overstock.github.io/library-detectors/index.html>

Sorry for the long delay!

  - Ian

**Pull request merged**
